Docker
pelican-dev/panel pull request #313
Opened 2024-06-03 01:57 UTC by lancepioch

2024-06-08 15:55 UTC, parkervcp requested changes
Need to update the `entrypoint.sh`. 

We should also have a `compose.yml` for easy automation

2024-06-08 15:55 UTC, parkervcp commented on .github/docker/entrypoint.sh
> +#chmod -R 775 storage/* bootstrap/cache/
remove this line

2024-06-08 15:55 UTC, parkervcp commented on .github/docker/entrypoint.sh
> +#chown -R caddy:caddy .
move to the `exec "$@"` and change `caddy:caddy` to `www-data:`

2024-06-08 19:48 UTC, engels74 commented
I'm not maintainer at all, but I still have a question :)

Previously, Pterodactyl Panel had a [quite long list](https://github.com/pterodactyl/panel/blob/develop/.env.example) of variables in its `.env.example` file. In this PR, the `.env.docker` file only has [a few variables](https://github.com/pelican-dev/panel/blob/577282094271076ac0977d8cc0fbcaaae46ba559/.env.docker). 

Is this intentional?

2024-06-10 12:54 UTC, parkervcp commented
> I'm not maintainer at all, but I still have a question :)
> 
> Previously, Pterodactyl Panel had a [quite long list](https://github.com/pterodactyl/panel/blob/develop/.env.example) of variables in its `.env.example` file. In this PR, the `.env.docker` file only has [a few variables](https://github.com/pelican-dev/panel/blob/577282094271076ac0977d8cc0fbcaaae46ba559/.env.docker).
> 
> Is this intentional?

From what I saw while testing, this runs a basic panel setup that uses an sqlite db. There are no variables needed for that.

2024-06-12 16:48 UTC, parkervcp approved these changes
Looks good to me. We should probably fire this up where it's actually on the internet to see how it goes before we fully release it.

We can add more compose files later. Some with all the things needed for redis/valkey and mariadb support.

2024-06-13 12:34 UTC, parkervcp requested changes

2024-06-13 12:34 UTC, parkervcp commented on compose.yml
> +volumes:
We need a volume for the certs that caddy generates.

2024-06-13 12:35 UTC, parkervcp commented on compose.yml
> +volumes:
We can use the `XDG_DATA_HOME` variable and set it to the same path as the pelican-data directory as well.

2024-06-13 13:32 UTC, parkervcp commented on compose.yml
> +volumes:
Should probably have a volume for logs as well.

2024-06-23 07:58 UTC, luthes commented
I've been digging into this a bit, both testing the Compose as well as the container builds, and tinkering with Helm. I run entirely in k8s any more, and having everything so tightly coupled in the current Dockerfile causes issues there.

That being said, I was able to split out Caddy and the Panel with Docker Compose (and Helm as well), by simply overriding commands, and editing and mounting the config file. But I do believe the base Dockerfile for the Panel should not bundle Caddy, each component (Caddy, Panel, Redis, etc.) should be it's own service.

From what I've been looking into this evening, what's needed to make this more micro-service friendly is:

     * Use volumes to provide access to `/var/www/html` files in Compose, rather than `COPY . .` in the Docker build.
     * Existing Panel Dockerfile should not bundle anything that's not necessary to running php-fpm. 
     * Caddyfile needs updated to use Docker overlay network, rather than localhost
     
Just a note that I'm willing to work on the above if you'd accept a PR. Let me know what you think of the above or if you're looking to go a different direction, happy to help.

2024-06-26 00:19 UTC, lancepioch commented
@luthes Can you please DM on Discord, I think you've got the right idea.

2024-07-23 15:34 UTC, parkervcp commented
I have read the CLA Document and I hereby sign the CLA

2024-07-28 20:05 UTC, parkervcp commented
@LumiKattlin did you have this issue while building the container? I just tried out a build and it worked.

Have you tried this recently?

2024-07-30 15:29 UTC, LumiKattlin commented
Yeah, dw, it ended up being a mistake on my part

ended up working :+1:

2024-09-18 17:35 UTC, VozDeOuro commented
@parkervcp sorry for ping, do you have any ETA on when this will be merged ?

2024-09-26 23:43 UTC, parkervcp commented
Well that was ugly

2024-09-27 13:06 UTC, parkervcp requested changes

2024-09-27 13:06 UTC, parkervcp commented on compose.yml
> +    APP_URL: "https://localhost" # can be set to 'http://localhost' to un on port 80 only
this should be defaulting to `http://` not `https://` it throws errors about certificates.

2024-09-27 16:05 UTC, parkervcp requested changes

2024-09-27 16:05 UTC, parkervcp commented on composer.json
> -        "ext-pdo_mysql": "*",
We need to support sql from the container still.

2024-09-27 22:00 UTC, parkervcp approved these changes
LGTM

2024-09-27 22:01 UTC, merged