Dashboard update. Update section
pelican-dev/panel pull request #390
Opened 2024-06-14 12:11 UTC by Poseidon281

Reopened PR to cleanup the comments at the suggestion of Lance

This PR makes a slight modification to the Dashboard so it now also displays that the panel is up to date

2024-06-14 12:46 UTC, Boy132 requested changes
Looks good, just some small adjustments.

2024-06-14 12:46 UTC, Boy132 commented on resources/views/filament/pages/dashboard.blade.php
> +    @if ($isLatest)
```suggestion
    @else
```

2024-06-14 12:46 UTC, Boy132 commented on lang/en/dashboard/index.php
> +            'content' => 'You are currently using :latestVersion. No update is available',
```suggestion
            'content' => 'You are currently using :version. Your panel is up-to-date!',
```

2024-06-14 12:46 UTC, Boy132 commented on lang/en/dashboard/index.php
> +        'intro-update-done' => [
```suggestion
        'intro-no-update' => [
```

2024-06-14 12:46 UTC, Boy132 commented on lang/en/dashboard/index.php
> +        'intro-update-need' => [
```suggestion
        'intro-update-available' => [
```

2024-06-14 12:46 UTC, Boy132 commented on resources/views/filament/pages/dashboard.blade.php
> +            <p>{{ trans('dashboard/index.sections.intro-update-need.content', ['latestVersion' => $latestVersion]) }}</p>
```suggestion
            <x-slot name="heading">{{ trans('dashboard/index.sections.intro-update-available.heading') }}</x-slot>

            <p>{{ trans('dashboard/index.sections.intro-update-available.content', ['latestVersion' => $latestVersion]) }}</p>
```

2024-06-14 12:46 UTC, Boy132 commented on resources/views/filament/pages/dashboard.blade.php
> +            <p>{{ trans('dashboard/index.sections.intro-update-done.content', ['latestVersion' => $latestVersion]) }}</p>
```suggestion
            <x-slot name="heading">{{ trans('dashboard/index.sections.intro-no-update.heading') }}</x-slot>

            <p>{{ trans('dashboard/index.sections.intro-no-update.content', ['version' => $version]) }}</p>
```

2024-06-14 12:46 UTC, Boy132 commented on resources/views/filament/pages/dashboard.blade.php
> +            id="intro-update-not-ready"
```suggestion
            id="intro-update-available"
```

2024-06-14 12:46 UTC, Boy132 commented on resources/views/filament/pages/dashboard.blade.php
> +            id="intro-update-ready"
```suggestion
            id="intro-no-update"
```

2024-06-14 14:22 UTC, Poseidon281 commented
> Looks good, just some small adjustments.

Thanks for the suggestions. I just added them

2024-06-16 18:34 UTC, Boy132 approved these changes
LGTM

2024-06-16 21:54 UTC, merged