Add missing foreign keys to fix #545
pelican-dev/panel pull request #549
Opened 2024-08-14 18:30 UTC by RMartinOscar

- [x] Make name & env_variables unique for each egg

> Throws a 500 if you try to add an duplicate

2024-08-20 07:40 UTC, Boy132 requested changes
Besides the backend changes we should also handle the frontend properly.

2024-08-20 07:40 UTC, Boy132 commented on database/migrations/2024_08_14_182737_fix_egg_variable_foreign_key.php
> +        if (Schema::getConnection()->getDriverName() !== 'sqlite') {
Fix needs to apply to all drivers, not just sqlite

2024-08-20 07:40 UTC, Boy132 commented on database/migrations/2024_08_14_182737_fix_egg_variable_foreign_key.php
> +        });
You don't need to drop and recreate the table to create an index. That is only needed when changing foreign keys on sqlite.

Create a new migration with something like this:
```php
Schema::table('egg_variables', function (Blueprint $table) {
    $table->unique(['egg_id', 'env_variable']);
    $table->unique(['egg_id', 'name']);
});
```

2024-08-20 07:40 UTC, Boy132 commented on database/migrations/2024_08_14_182737_fix_egg_variable_foreign_key.php
> +        // Reverse not needed
```php
Schema::table('egg_variables', function (Blueprint $table) {
    $table->dropUnique(['egg_id', 'env_variable']);
    $table->dropUnique(['egg_id', 'name']);
});
```

2024-08-20 20:40 UTC, RMartinOscar commented
@Boy132 sqlite tests are still failling

2024-09-06 09:00 UTC, Boy132 commented
> @Boy132 sqlite tests are still failling

I found the reason: the `sort` for the bungeecord variables is `null`. For all other eggs the `sort` is filled.

2024-09-07 16:46 UTC, notAreYouScared commented
@RMartinOscar Can you merge main, and see if the tests pass?

2024-10-20 21:18 UTC, lancepioch commented
We should programmatically enforce this instead, I think sqlite has an issue with composite unique keys.

2024-10-20 21:18 UTC, closed without merging