Remove old admin area
pelican-dev/panel pull request #648
Opened 2024-10-20 21:10 UTC by lancepioch

2024-10-21 13:20 UTC, RMartinOscar commented on routes/console.php
Should we make a new override under `App\Console\Commands\Overrides\ServeCommand.php` ?

2024-10-21 16:28 UTC, lancepioch commented on routes/console.php
Artisan Serve (PHP built in webserver) doesn't work with the React app we have, but we're replacing that and it works perfectly well with Filament.

2024-10-21 16:29 UTC, lancepioch commented on app/Listeners/Auth/PasswordResetListener.php
> -<?php
It doesn't look to be referenced or used anywhere.

2024-10-21 16:29 UTC, lancepioch commented on app/Listeners/Auth/TwoFactorListener.php
> -<?php
It doesn't look to be referenced or used anywhere.

2024-10-21 16:30 UTC, lancepioch commented on resources/views/vendor/notifications/email.blade.php
> -<!DOCTYPE html>
It doesn't look to be referenced or used anywhere.

2024-10-21 16:30 UTC, lancepioch commented on resources/views/vendor/notifications/email-plain.blade.php
> -<?php
It doesn't look to be referenced or used anywhere.

2024-10-21 16:44 UTC, Boy132 commented on resources/views/vendor/notifications/email.blade.php
> -<!DOCTYPE html>
Well, that's our email template. If we remove that we either get non working emails or emails in the default template (if such thing exists)

2024-10-21 16:54 UTC, Boy132 commented on app/Listeners/Auth/AuthenticationListener.php
> -<?php
![image](https://github.com/user-attachments/assets/d5cc1e40-8da0-48af-9b01-02aa4fe81b34)
![image](https://github.com/user-attachments/assets/5bc5a113-8be6-4245-bbd8-9b10276a782b)

2024-10-22 00:38 UTC, lancepioch commented on app/Listeners/Auth/AuthenticationListener.php
> -<?php
That's very interesting, thanks, nice catch, I'll add it back!

2024-10-22 06:36 UTC, Boy132 commented on app/Listeners/Auth/AuthenticationListener.php
> -<?php
Yeah, you can't always trust phpstorms "no usages". Many things are used/ called indirectly by Laravel.
(fyi https://laravel.com/docs/11.x/events#defining-listeners)

2024-10-27 16:38 UTC, RMartinOscar commented
`app/Exceptions/Solutions/ManifestDoesNotExistSolution.php`
and
https://github.com/pelican-dev/panel/blob/73f056c1c879ba896103709387a7d8f4c2fe8c50/composer.json#L53
should also get removed now that its not used anywhere.

2024-10-31 09:42 UTC, lancepioch commented
@RMartinOscar ignition solutions are used in debug mode

2024-10-31 21:52 UTC, Boy132 approved these changes

2024-11-05 20:14 UTC, Boy132 requested changes

2024-11-05 20:14 UTC, Boy132 commented on resources/views/templates/wrapper.blade.php
> -        @show
This is needed for the client area.

2024-11-05 20:14 UTC, Boy132 commented on app/Http/ViewComposers/AssetComposer.php
> -        $view->with('asset', $this->assetHashService);
Needed for the client area.

2024-11-05 20:14 UTC, Boy132 commented on app/Services/Helpers/AssetHashService.php
> -}
Needed for the client area.

2024-11-06 21:26 UTC, notAreYouScared commented
The client ar
ea is working as expected. LGTM

@Boy132 @RMartinOscar Could you still take a look at it?

2024-11-06 21:26 UTC, notAreYouScared approved these changes

2024-11-07 01:40 UTC, RMartinOscar commented
![image](https://github.com/user-attachments/assets/42aff5be-2fc9-48a2-af28-7f35d992f2be)
When clicking autoDeploy

2024-11-09 19:38 UTC, Boy132 approved these changes

2024-11-13 22:05 UTC, merged