Clear webhook cache when webhooks are deleted
pelican-dev/panel pull request #695
Opened 2024-10-31 20:20 UTC by lancepioch

Fixes #689

2024-11-01 01:12 UTC, RMartinOscar commented on app/Models/WebhookConfiguration.php
> +            self::updateCache(collect($webhookConfiguration->events));
```suggestion
            self::updateCache((array) collect($webhookConfiguration->events));
```

2024-11-01 01:12 UTC, RMartinOscar commented on app/Models/WebhookConfiguration.php
> +    private static function updateCache($eventList): void
```suggestion
    private static function updateCache(Collection $eventList): void
```

2024-11-01 17:57 UTC, RMartinOscar commented on app/Models/WebhookConfiguration.php
> +            self::updateCache(collect($webhookConfiguration->events));
```suggestion
            self::updateCache((array) collect($webhookConfiguration->events));
```

2024-11-01 23:44 UTC, RMartinOscar commented on app/Models/WebhookConfiguration.php
> +            self::updateCache(collect($webhookConfiguration->events));
```suggestion
            self::updateCache(collect((array) $webhookConfiguration->events));
```

2024-11-01 23:44 UTC, RMartinOscar commented on app/Models/WebhookConfiguration.php
> +    private static function updateCache($eventList): void
```suggestion
    private static function updateCache(Collection $eventList): void
```

2024-11-01 23:45 UTC, RMartinOscar requested changes
Add this on top
```php
use Illuminate\Support\Collection;
```

2024-11-07 22:19 UTC, RMartinOscar approved these changes

2024-11-07 22:26 UTC, notAreYouScared approved these changes

2024-11-07 22:26 UTC, merged