Write special env variables at the very end of the installer
pelican-dev/panel pull request #699
Opened 2024-11-01 17:14 UTC by Boy132

Closes #696

This makes sure that "special" env variables (in this case the `SESSION_DRIVER`) are only written to the .env file at the very end of the installer.
The `SESSION_DRIVER` variable is the only variable that directly affects the installer when being changed.

2024-11-01 17:48 UTC, RMartinOscar commented
https://github.com/pelican-dev/panel/blob/382dcb3868395a7753940e49d358f51719241927/app/Filament/Pages/Installer/PanelInstaller.php#L74
```
$get('env_special.SESSION_DRIVER')
$get('env_special.CACHE_STORE')
```
https://github.com/pelican-dev/panel/blob/382dcb3868395a7753940e49d358f51719241927/app/Filament/Pages/Installer/Steps/EnvironmentStep.php#L63

We have to change those too

2024-11-01 17:49 UTC, RMartinOscar requested changes
https://github.com/pelican-dev/panel/blob/382dcb3868395a7753940e49d358f51719241927/app/Filament/Pages/Installer/PanelInstaller.php#L74
```
$get('env_special.SESSION_DRIVER')
$get('env_special.CACHE_STORE')
```
https://github.com/pelican-dev/panel/blob/382dcb3868395a7753940e49d358f51719241927/app/Filament/Pages/Installer/Steps/EnvironmentStep.php#L63

We have to change those too

2024-11-01 18:02 UTC, Boy132 commented
> https://github.com/pelican-dev/panel/blob/382dcb3868395a7753940e49d358f51719241927/app/Filament/Pages/Installer/PanelInstaller.php#L74
> 
> ```
> ->hidden(fn (Get $get) => $get('env_special.SESSION_DRIVER') != 'redis' && $get('env_general.QUEUE_CONNECTION') != 'redis' && $get('env_special.CACHE_STORE') != 'redis'), 
> ```
> 
> https://github.com/pelican-dev/panel/blob/382dcb3868395a7753940e49d358f51719241927/app/Filament/Pages/Installer/Steps/EnvironmentStep.php#L63
> 
> ```
> ToggleButtons::make('env_special.CACHE_STORE') 
> ```
> 
> We have to change those too

Hidden check is fixed. And the cache driver is fine, it doesn't need special treatment.

2024-11-01 18:11 UTC, RMartinOscar commented
I had the same 500 as before when hitting next in the db step with redis selected as cache store it errors immediately i can't even fill in the redis pass so it uses no password cause no redis env is set yet.
This is fixed with my proposed changes.

2024-11-06 08:10 UTC, Boy132 commented
> I had the [same 500](https://github.com/pelican-dev/panel/issues/623#issuecomment-2411617308) as before when hitting next in the db step with redis selected as cache store it errors immediately i can't even fill in the redis host & pass so it uses no password cause no redis env is set yet. This is fixed with my proposed changes.
> 
> > Using redis which is on something else but localhost will also throw

Please try again and if you still get a 500 post the error.
The error you linked is also from the session driver and not the cache.

2024-11-07 18:27 UTC, RMartinOscar commented
> > I had the [same 500](https://github.com/pelican-dev/panel/issues/623#issuecomment-2411617308) as before when hitting next in the db step with redis selected as cache store it errors immediately i can't even fill in the redis host & pass so it uses no password cause no redis env is set yet. This is fixed with my proposed changes.
> > > Using redis which is on something else but localhost will also throw
> 
> Please try again and if you still get a 500 post the error. The error you linked is also from the session driver and not the cache.

https://paste.pelistuff.com/kin4

2024-11-07 22:29 UTC, lancepioch commented
We should validate the Redis connection too and make sure it works before saving it in the .env, good catch!

2024-11-07 23:00 UTC, Boy132 commented
> > > I had the [same 500](https://github.com/pelican-dev/panel/issues/623#issuecomment-2411617308) as before when hitting next in the db step with redis selected as cache store it errors immediately i can't even fill in the redis host & pass so it uses no password cause no redis env is set yet. This is fixed with my proposed changes.
> > > > Using redis which is on something else but localhost will also throw
> > 
> > 
> > Please try again and if you still get a 500 post the error. The error you linked is also from the session driver and not the cache.
> 
> https://paste.pelistuff.com/kin4 I only selected cache store in the first step

Yeah so that's a totally different error...

> We should validate the Redis connection too and make sure it works before saving it in the .env, good catch!

The redis connection is validated - in the Redis step.

The problem is the `SoftwareVersionService` that gets called when we run the config clear command. (I assume that's because of dependency injection)

2024-11-08 22:39 UTC, closed without merging