Support multiple nodes on database hosts
pelican-dev/panel pull request #724
Opened 2024-11-21 21:00 UTC by alexevladgabriel

Closes #133

2024-11-22 02:07 UTC, RMartinOscar requested changes
MySql/Mariadb needs explicit type

2024-11-22 02:07 UTC, RMartinOscar commented on database/migrations/2024_10_31_203540_change_database_hosts_to_belong_to_many_nodes.php
> +            $table->id();
```suggestion
            $table->id();
            $table->unsignedInteger('node_id');
```

2024-11-22 02:07 UTC, RMartinOscar commented on database/migrations/2024_10_31_203540_change_database_hosts_to_belong_to_many_nodes.php
> +            $table->foreignId('node_id')->nullable()->references('id')->on('nodes');
```suggestion
            $table->unsignedInteger('node_id')->nullable();
            $table->foreignId('node_id')->references('id')->on('nodes');
```

2024-12-05 21:13 UTC, notAreYouScared commented
Closed in favor of #767

2024-12-05 21:13 UTC, closed without merging