Add role permissions for webhooks
pelican-dev/panel pull request #742
Opened 2024-12-01 16:04 UTC by Boy132

2024-12-01 22:51 UTC, RMartinOscar commented
Can't view webhook you should be able to access the edit page but everything should be read only (we can even hide events that are not active for better userfriendlyness)
![image](https://github.com/user-attachments/assets/2b9f6a19-170e-4218-9bb6-b2f21a4299d3)
![image](https://github.com/user-attachments/assets/50457149-4cdc-463c-865b-5cd586da249e)

![image](https://github.com/user-attachments/assets/65b96ab9-a614-4948-b46b-f1218abcdb43)

2024-12-01 22:52 UTC, RMartinOscar requested changes
Can't view webhook you should be able to access the edit page but everything should be read only (we can even hide events that are not active for better userfriendlyness)
![image](https://github.com/user-attachments/assets/2b9f6a19-170e-4218-9bb6-b2f21a4299d3)
![image](https://github.com/user-attachments/assets/50457149-4cdc-463c-865b-5cd586da249e)
![image](https://github.com/user-attachments/assets/daa7afaf-1975-48e4-9247-4b7e2e3ae614)

2024-12-02 20:55 UTC, Boy132 commented
> Can't view webhook you should be able to access the edit page but everything should be read only (we can even hide events that are not active for better userfriendlyness)

See #583

2024-12-02 21:28 UTC, RMartinOscar approved these changes

2024-12-02 22:18 UTC, notAreYouScared approved these changes

2024-12-02 22:53 UTC, merged