Delete subuser on owner change
pelican-dev/panel pull request #748
Opened 2024-12-02 01:40 UTC by RMartinOscar

2024-12-02 07:41 UTC, Boy132 requested changes

2024-12-02 07:41 UTC, Boy132 commented on app/Filament/Resources/ServerResource/Pages/EditServer.php
> +
Move this to the Server model and use model events.

```php
// Pseudo code
protected static function booted(): void
{
    static::saved(function (self $server) {
        $subuser = Subuser::query()->where('user_id', $server->owner_id)->where('server_id', $server->id)->first();
        if ($subuser) {
            $this->subuserDeletionService->handle($subuser, $server);
        }
    });
}
```

2024-12-03 12:48 UTC, Boy132 approved these changes

2024-12-03 22:34 UTC, notAreYouScared approved these changes

2024-12-03 22:55 UTC, merged